"""add posts table2

Revision ID: cbe939c3815d
Revises: 98074bd2284a
Create Date: 2025-02-19 14:41:27.503778

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cbe939c3815d'
down_revision = '98074bd2284a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_id'), 'post', ['id'], unique=False)
    op.create_index(op.f('ix_post_owner_id'), 'post', ['owner_id'], unique=False)
    op.create_index(op.f('ix_post_title'), 'post', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_title'), table_name='post')
    op.drop_index(op.f('ix_post_owner_id'), table_name='post')
    op.drop_index(op.f('ix_post_id'), table_name='post')
    # ### end Alembic commands ###
